TuringLang/DistributionsAD.jl

Manifest.toml, test/runtests.jl
This PR moves `Truncated` to the tested distributions. This PR should pass tests after https://github.com/JuliaStats/Distributions.jl/pull/991 is merged and released.
=> Test Truncated

Manifest.toml, Project.toml, src/common.jl, test/test_utils.jl
Depends on the following PRs:
`DistributionsAD` currently breaks for newer versions of `Zygote` and other related/dependent packages, including `Turing`. The lower-bounds in this PR provide a fix.
UPDATE: both PRs have been merged, now we're just waiting for relases to happen.
=> Add compatibilities and bump patch version

src/multivariate.jl
This PR fixes the performance hit with `MvNormal` and `MvLogNormal` noticed in https://github.com/TuringLang/DynamicPPL.jl/issues/26.
=> Fix MvNormal and LogMvNormal perf

src/common.jl
Fixes the method ambiguity errors seen in Turing's CI tests (see, e.g., https://github.com/TuringLang/Turing.jl/pull/1063).
BTW I had some issues reproducing the error locally after skipping some other tests - `import/using`s and definitions/settings of tests that are run prior to the distribution tests affect them. Maybe one could think about using [SafeTestsets](https://github.com/YingboMa/SafeTestsets.jl) to avoid such issues.
=> Fix method ambiguity

src/common.jl
TrackedVecOrMat is already defined in https://github.com/FluxML/Tracker.jl/blob/128c29d46d51e182319bbdbae066dc279bdee2af/src/lib/array.jl#L22, so the definition in DistributionsAD can be removed.
=> Do not redefine TrackedVecOrMat

src/multivariate.jl
Fixed bug in implementation of `size` for `TuringScalMvNormal`. `size(d::MultivariateDistribution)` should return `(length(d), )` not `(length(d), length(d))`.
=> Fixed bug in implementation of `size`

src/for.jl
This PR adds the `For` combinator from Soss.jl. I usually use it like this:
```julia
x ~ For(indices) do j
someDistribution(j)
end
```
`indices::T` can have...
- `T <: NTuple{N,J} where {J <: Integer}` 
- `T <: NTuple{N,J} where {J <: AbstractUnitRange}`
- `T <: Base.Generator` (for example to use with `eachrow`)
For a single index, there's no need to write this an a 1-tuple, that conversion is done automatically
=> Add for.jl

src/common.jl
Compat already implements `eachcol` for old Julia versions.
=> Remove definition of eachcol

.github/workflows/ForwardDiff_Tracker.yml, .github/workflows/Others.yml, .github/workflows/Zygote.yml, test/others.jl, test/test_utils.jl
This PR fixes the spontaneous segfaulting that happens in Zygote tests. It worked locally when I called refresh after every distribution but it took a long time. Let's see if this passes tests.
=> Call Zygote.refresh every 10 distributions in tests

Project.toml, src/DistributionsAD.jl, src/common.jl, test/others.jl, test/runtests.jl
This PR removes the redundant cholesky adjoint and works around https://github.com/FluxML/Tracker.jl/pull/9#issuecomment-480051767. This PR depends on https://github.com/FluxML/Zygote.jl/pull/539.
=> Some linear algebra fixes

Project.toml
It requires an old Combinatorics package, which may cause conflicts with other packages.
=> fix project.toml

src/reversediff.jl
It seems that `materialize` is not exported out of `Base.Broadcast` in Julia 1.0.5. This PR fixes the issue in https://github.com/TuringLang/Turing.jl/issues/1164#issuecomment-602054067.
=> materialize fix on Julia 1.0.5

.github/workflows/CompatHelper.yml, .github/workflows/ForwardDiff_Tracker.yml, .github/workflows/Others.yml, .github/workflows/ReverseDiff.yml, .github/workflows/TagBot.yml, .github/workflows/Zygote.yml, src/reversediff.jl, src/univariate.jl
This PR updates all CI tests to run on Julia 1.4 and 1.0 and reduces the frequency of TagBot and CompatHelper to once per day. Although intended otherwise, CI tests were not run on Julia 1.0 before (`[1.0, 1.3]` is interpreted as `[1, 1.3]`).
=> Update and fix CI tests

Project.toml, src/DistributionsAD.jl, src/arraydist.jl, src/common.jl, src/filldist.jl, src/matrixvariate.jl, src/multivariate.jl, src/reversediff.jl, src/reversediffx.jl, src/univariate.jl
This PR removes the Zygote dependency, as discussed in https://github.com/TuringLang/DistributionsAD.jl/issues/65#issuecomment-619516746. Moreover, currently sometimes the explicit `ZygoteRules.@adjoint` and `ZygoteRules.pullback` was used and sometimes only `@adjoint` and `pullback`. I reformatted the code (adhering to the 92 characters limit) so that now consistently the more explict `ZygoteRules.@adjoint` and `ZygoteRules.pullback` are used to show clearly that these implementations use Zygote.
=> Drop Zygote dependency and reformat code

src/common.jl, src/reversediff.jl, src/reversediffx.jl, test/others.jl
This PR refactors the cholesky adjoints and extends them to handle the cholesky of matrices wrapped by `Symmetric`. Some tests were moved from Turing to this repo. Also the `ReverseDiff.@grad` tests were removed from this repo because they exist in `ReverseDiff` now.
=> Support cholesky of Symmetric and refactor some tests

src/multivariate.jl, src/reversediff.jl
This PR fixes a performance regression in the LDA and hmm_semisup benchmarks in TuringExamples when using the latest release of DistributionsAD compared to the branch used in TuringExamples#master.
=> Define custom adjoint for simplex_logpdf

src/multivariate.jl
The Tracker custom adjoint for `simplex_logpdf` introduced in #75 seems to be causing issues over in Turing. I don't have time to investigate why so I am removing them for now, keeping the ReverseDiff and Zygote ones.
=> Remove Tracker custom grad for simplex_logpdf

src/reversediffx.jl
This PR uses non-tracked types in the custom adjoint rules of ReverseDiff. This is the right way to do it especially for functions with 2 or more arguments to allow mixed tracked and untracked inputs.
=> Use non-tracked types in `@grad` definitions

src/multivariate.jl, src/reversediff.jl, test/ad/utils.jl
@mohamed82008 noticed that both the previous and the updated test sets (the logic was unchanged) don't test AD with respect to samples `x` and fixed distribution parameters `theta` if `theta` is not empty (only the case when `theta` was empty was covered). This PR adds these additional tests.
Actually, in my local runs some of these tests seem to be broken (see, e.g., https://github.com/TuringLang/DistributionsAD.jl/issues/91) and fail currently. I'm a bit surprised that this hasn't shown up in the other tests with at least one non-fixed distribution parameter.
Somehow the automatic code formatting in VSCode introduced some additional changes...
=> Test AD wrt `x` and fixed `theta` if possible

test/ad/distributions.jl, test/ad/utils.jl
I have just been looking into how to test whether particular backends are broken using `@test_broken`. If this looks good to @devmotion, I can have a go at adding the relevant broken backends to the broken tests.
Ref #93 and https://github.com/TuringLang/Bijectors.jl/pull/116#discussion_r443399529
Example on a randomly chosen broken test:
```julia
julia> d = DistSpec(
p -> Multinomial(2, p ./ sum(p)),
(fill(0.5, 2),),
[2 1; 0 1],
broken=("Tracker", "Zygote"),
);
julia> test_ad(d)
[ Info: Testing: Multinomial
julia> d = DistSpec(
p -> Multinomial(2, p ./ sum(p)),
(fill(0.5, 2),),
[2 1; 0 1],
);
julia> test_ad(d)
[ Info: Testing: Multinomial
Error During Test at /Users/harry/git/julia_sandbox/tmp.jl:213
Test threw exception
Expression: ≈(Tracker.data((Tracker.gradient(f, x))[1]), …
```
=> WIP test broken backends

.github/workflows/ForwardDiff.yml, .github/workflows/Others.yml, .github/workflows/ReverseDiff.yml, .github/workflows/Tracker.yml, .github/workflows/Zygote.yml, Project.toml, test/ad/distributions.jl
Tracker issues related to PDMats 0.10 are fixed in the recent release of Tracker which, however, is not available on Julia < 1.3. To avoid having to backport fixes to earlier Julia versions, we drop support of Julia < 1.3 and add tests for Julia 1.3 (probably, waiting for more comments on https://discourse.julialang.org/t/rfc-dropping-support-for-julia-1-3-in-turing-jl/45015).
=> Require Julia 1.3

src/tracker.jl
As discussed with @DhairyaLGandhi it would make sense to move these functions to Tracker.jl
=> Fix TrackedReal nextfloat and prevfloat

Project.toml, src/DistributionsAD.jl, src/common.jl, src/multivariate.jl, src/univariate.jl
My attempt to fix #98 for `TuringMvNormal` by `@require`ing `CUDA`. What do you think?
=> Fix TuringMvNormal's rand on GPU

Project.toml, src/common.jl, src/forwarddiff.jl, src/reversediff.jl, src/tracker.jl, test/others.jl
This PR fixes some of the test errors on Turing that are caused by `adapt_randn` (e.g., https://travis-ci.com/github/TuringLang/Turing.jl/jobs/383997198).
=> Fix `adapt_randn` for tracked arrays

Project.toml, src/multivariate.jl, src/reversediff.jl, src/tracker.jl, test/others.jl, test/runtests.jl
This PR fixes https://github.com/TuringLang/Turing.jl/issues/1530 by relaxing the type constraints of `TuringDirichlet`, in line with recent updates in Distributions that allow integer-valued parameters.
It should also be more efficient to use `Fill` instead of `fill` (again in line with changes in Distributions).
I added some tests. Tests of Turing master pass locally with this PR.
=> Fix and test `TuringDirichlet` constructors

Project.toml, src/reversediff.jl
The issue was fixed upstream in ReverseDiff.
=> Remove workaround for `view` with ReverseDiff

Project.toml, src/DistributionsAD.jl, src/common.jl, src/forwarddiff.jl
This PR fixes errors with Adapt 3.3.0 (see https://github.com/SciML/OrdinaryDiffEq.jl/issues/1369#issuecomment-817286051 for an explanation why it broke `adapt_randn`).
Additionally, I used the opportunity to replace the custom `rrule` with `@non_differentiable` which now supports varargs (moreover, it defines a `frule` as well and uses an optimized definition with `@nospecialize`).
=> Fix errors with Adapt 3.3.0

Project.toml, src/DistributionsAD.jl, src/reversediff.jl
This PR fixes https://github.com/TuringLang/DistributionsAD.jl/issues/163 for me locally.
@gideonsimpson can you check that it fixes the warning for you as well? You can install this branch with
```julia
julia> ] add DistributionsAD#dw/forwarddiff
```
=> Load ForwardDiff correctly

src/multivariate.jl, test/others.jl
This addresses https://github.com/TuringLang/DistributionsAD.jl/issues/158 (at least partly, the differentials are not adjusted yet). I made these changes a while ago but forgot to open a PR.
In an ideal future we would just define the differentials (if needed) and remove the type and logpdf computation from DistributionsAD. But better we fix it as long as it exists :slightly_smiling_face:
=> Fix `simplex_logpdf` for values outside of the support

src/univariate.jl
Since we only support Julia >= 1.3.
=> Remove special case for Julia < 1.2

Project.toml, src/matrixvariate.jl
Broken by https://github.com/JuliaStats/Distributions.jl/pull/1429.
(I really hate these reimplementations that are based on outdated and diverging copies of code from Distributions...)
=> Fix `_wishart_genA!`

Project.toml, src/arraydist.jl
`Product` is deprecated in favour of `product_distribution` in Distributions >0.25.64.
=> Fix deprecation warnings of `Product` constructor

src/arraydist.jl, src/filldist.jl, test/Project.toml, test/ad/distributions.jl, test/ad/utils.jl
Switch `logpdf(::FillDist)` from `sum(map(f, x))` to `mapreduce(f, +, x)` to eliminate the unnecessary array allocations.
`sum(f, x)` would have been even simpler, but I'm hitting `*(::TrackedReal, ::Dual)` method ambiguity on this path.
It's beyond my current understanding of the autodiff code to figure out whether just this change breaks some tests (`Chernoff` distribution) and fixes other (`Zygote`) or it is just a coincidence.
I have tried to `@benchmark` the change, but with `@benchmark(logpdf($(filldist(Cauchy(), 1000)), $(rand(1000))))` I don't see much of the change.
I guess it starts to be visible with dual numbers.
So here's the profiling results.
Before:
After:
Note that array allocation and copying disappear, and it looks like overall it should be ~30% faster.
=> Faster filldist()

ext/DistributionsADTrackerExt.jl
They're unneeded, and breaking on Julia master:
https://github.com/JuliaLang/julia/commit/feb2988b3a21968410267378b910ce67726a51d8
=> Remove type parameters

Project.toml, src/multivariate.jl, test/others.jl
This PR shows what I had in mind when commenting on #258.
Should fix #156 but is quickly typed on my mobile phone and untested.
=> Fix promotions with irrationals

Project.toml
Adapt v4.0.0 features breaking changes in `Adapt.ndims`, `Adapt.eltype` and `Adapt.parent`
(see https://github.com/JuliaGPU/Adapt.jl/releases/tag/v4.0.0)
DistributionsAD.jl seems to be using only `Adapt.adapt` [here](https://github.com/TuringLang/DistributionsAD.jl/blob/b7c2184b7791fa5f379ef3948e760961890eb40f/src/common.jl#L42), so it should not be affected by the changes in Adapt v4.0.0.
Closes #262.
=> Bump compat for Adapt to 4

src/filldist.jl
Possibly this fixes the method ambiguity issues in #264. At least it shows that there is an inconsistency in the definition of `filldist` currently - most methods are defined for `Int`s but one is defined for `Integer`s.
=> Fix MethodAmbiguity errors

src/filldist.jl
Checking the output of `rand(d)` in a doc test is very brittle, even when setting a seed or even with StableRNGs. For instance, https://github.com/JuliaStats/Distributions.jl/pull/1905 breaks this doctest.
=> Don't check result of `rand(d)` in doc tests
